# Generated by Django 4.1.1 on 2022-09-18 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inhabitants', '0001_initial'),
        ('creatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=150)),
                ('history', models.CharField(default=None, max_length=1000)),
                ('trivia', models.CharField(default=None, max_length=200)),
                ('location_image_1', models.CharField(default=None, max_length=300)),
                ('location_image_2', models.CharField(default=None, max_length=300)),
                ('location_image_3', models.CharField(default=None, max_length=300)),
                ('youtube_id', models.CharField(default=None, max_length=100)),
                ('risk', models.CharField(blank=True, choices=[('Low Risk', 'Low Risk'), ('Medium Risk', 'Medium Risk'), ('High Risk', 'High Risk')], max_length=100)),
                ('creatures', models.ManyToManyField(blank=True, related_name='creatures', to='creatures.creature')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='location_dislike', to=settings.AUTH_USER_MODEL)),
                ('favourites', models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL)),
                ('inhabitants', models.ManyToManyField(blank=True, related_name='inhabitants', to='inhabitants.inhabitant')),
                ('likes', models.ManyToManyField(blank=True, related_name='location_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
